'use client';
import { useEffect, useState } from 'react';
import { LoaderCircle, Sparkles } from 'lucide-react';
import { api } from '@/lib/api';
import type { AiInsightRun } from '@/lib/types';

// Generated only on request: each click sends the overview's totals to OpenAI once.
export function AiInsightsPanel({ datasetId, aiConfigured }: { datasetId: string; aiConfigured: boolean }) {
  const [run,setRun]=useState<AiInsightRun|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  useEffect(()=>{let active=true;api<AiInsightRun[]>(`/datasets/${datasetId}/ai-insights`).then(r=>{if(active)setRun(r[0]??null);}).catch(e=>{if(active)setError((e as Error).message);});return()=>{active=false;};},[datasetId]);
  async function generate() {
    setBusy(true);setError('');
    try{setRun(await api<AiInsightRun>(`/datasets/${datasetId}/ai-insights`,{method:'POST'}));}
    catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  const when=run?new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(run.createdAt)):'';
  return <section className="ai-insights" aria-label="AI insights">
    <div className="ai-insights-head"><span className="ai-insights-icon"><Sparkles size={16}/></span><div><h2>AI insights</h2><p>{aiConfigured?'Sends chart totals to OpenAI — no rows or protected columns.':'AI insights needs an OpenAI API key on the app server.'}</p></div><button className="ai-generate" onClick={generate} disabled={!aiConfigured||busy}>{busy?<><LoaderCircle className="spin" size={14}/> Generating…</>:run?'Regenerate':'Generate AI insights'}</button></div>
    {error&&<p role="alert" className="error-note">{error}</p>}
    {run&&<><ul className="insight-list">{run.insights.map(i=><li key={i.title}><Sparkles size={15}/><div><p><strong>{i.title}.</strong> {i.text}</p><span>Source: <code>{i.source}</code></span></div></li>)}</ul><p className="ai-insights-meta">AI-generated by {run.model} · {when} · Check figures against the charts below.</p></>}
  </section>;
}
